// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbdb4vv-xafacUvhMMUx9IUVqXyIajdCs',
    appId: '1:1092392142377:android:171317002db3af15127e38',
    messagingSenderId: '1092392142377',
    projectId: 'reactchat-8ebc9',
    databaseURL: 'https://reactchat-8ebc9-default-rtdb.firebaseio.com',
    storageBucket: 'reactchat-8ebc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0R6JnlkLoBukoH7FruiYL8rgBHuHG_r4',
    appId: '1:1092392142377:ios:0766a3578ac2fde3127e38',
    messagingSenderId: '1092392142377',
    projectId: 'reactchat-8ebc9',
    databaseURL: 'https://reactchat-8ebc9-default-rtdb.firebaseio.com',
    storageBucket: 'reactchat-8ebc9.appspot.com',
    iosBundleId: 'com.example.modoTour',
  );
}
